# Generated by Django 5.1.2 on 2024-12-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_users_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='money_balance',
            field=models.IntegerField(default=0),
        ),
    ]
