# Generated by Django 5.1.2 on 2024-10-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_reviews_owner_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='product_imgs'),
        ),
    ]
