# Generated by Django 5.1.2 on 2024-10-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_category_cat_name_alter_products_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(max_length=30),
        ),
    ]
