# Generated by Django 5.1.2 on 2024-10-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basket_sum', models.IntegerField(default=0)),
                ('product_quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
