# Generated by Django 5.1.2 on 2024-10-27 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_basket_basket_sum_and_more'),
        ('products', '0003_products_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='products',
        ),
        migrations.AlterField(
            model_name='basket',
            name='basket_sum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='basket',
            name='product_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Product_in_basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
                ('where_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.basket')),
            ],
        ),
    ]
