# Generated by Django 5.1.2 on 2024-12-10 16:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_refounds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Refounds',
            new_name='Refunds',
        ),
        migrations.RenameField(
            model_name='refunds',
            old_name='refound',
            new_name='refund',
        ),
        migrations.RenameField(
            model_name='refunds',
            old_name='whose_refound',
            new_name='whose_refund',
        ),
    ]
