# Generated by Django 5.1.2 on 2024-12-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_refunds_refund_applicationonrefund'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationonrefund',
            name='accept',
            field=models.BooleanField(blank=True, default='', null=True),
        ),
    ]
