# Generated by Django 5.1.2 on 2024-12-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_applicationonrefund_accept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationonrefund',
            name='accept',
        ),
        migrations.AddField(
            model_name='refunds',
            name='accept',
            field=models.BooleanField(blank=True, default='', null=True),
        ),
    ]
