# Generated by Django 5.1.2 on 2024-12-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_remove_applicationonrefund_accept_refunds_accept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refunds',
            name='accept',
        ),
        migrations.AddField(
            model_name='applicationonrefund',
            name='accept',
            field=models.BooleanField(blank=True, default='', null=True),
        ),
    ]
